# Site settings
title: --Jean Arreola--
description: Personal website with all my crazy ideas.
url: " http://jean9208.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jean Arreola
user_description: Actuarial Coordinator at HDI Seguros
user_title: Statistics, Code and Stuff
email: jean.arreola@yahoo.com.mx
#twitter_username: lorem_ipsum
github_username:  jean9208
#gplus_username:  lorem_ipsum
disqus_username: https-jean9208-github-io

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about
  - title: Links
    url: /links

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
